#!/bin/zsh

# Se parte de que la carpeta del proyecto eśta
# ubicada dos niveles por encima de la del script
REL=../..

# averigua el directorio que aloja el script
SCRIPT=$(readlink -f $0);
SDIR=`dirname $SCRIPT`

# ruta al directorio del projecto
SCRIPT=$(readlink -f "$SDIR/$REL/some");
PDIR=`dirname $SCRIPT`

#configura con cmake
$SDIR/config
RES=$?
if test $RES -gt 0; then
    exit $RES
fi

cd $PDIR/build
cmake --build .
RES=$?
echo --------------------------------------------------------------------------------
exit $RES
