#!/bin/sh

# Se parte de que la carpeta del proyecto está
# ubicada dos niveles por encima de la del script
REL=../..

# averigua el directorio que aloja el script
SCRIPT=$(readlink -f $0);
SDIR=`dirname $SCRIPT`

# ruta al directorio del projecto
SCRIPT=$(readlink -f "$SDIR/$REL/some");
PDIR=`dirname $SCRIPT`

cd $PDIR
rm -fr  ./build
echo configutarion removed

